export const rep = [
  {
    response:
      '{\n  "title": "Evaluering av supervisionssamtale",\n  "introduction": "Velkommen til evaluering av denne supervisionssamtalen!",\n  "techniques": [\n    { "name": "Empati", "description": "Supervisor ser på traineens perspektiv og uttrykker forståelse." },\n    { "name": "Fokus på trainees egne refleksjoner", "description": "Supervisor oppmuntrer traineen til å reflektere over egen utvikling og utfordringer." }\n  ],\n  "limitations": [\n    "Manglet en mer konkrete plan for hvordan trainee kan arbeide på å løse sine utfordringer."\n  ],\n  "summary": "Denne samtalen viser god bruk av empati og fokus på trainees egne refleksjoner. Supervisor har lyktes i å skape en trygg og åpen atmosfære, men kunne hatt mer fokus på konkrete planer for utvikling."\n}',
  },
  {
    response:
      '{\n  "title": "Evaluering av supervisionssamtale",\n  "introduction": "Velkommen til evaluering av denne supervisionssamtalen!",\n  "techniques": [\n    { \n      "name": "Empati", \n      "description": "Supervisor ser på traineens perspektiv og uttrykker forståelse. Supervisor spør etter detaljer om hvordan traineen føler seg, og respekterer deres erfaringer." \n    },\n    { \n      "name": "Fokus på egne forslag", \n      "description": "Supervisor oppmuntrer traineens egne refleksjon over egen utvikling. Supervisor stiler ikke selv alle spørsmål, men lar traineen komme med sine egne tanker og erfaringer."\n    },\n    { \n      "name": "Refleksjon", \n      "description": "Supervisor oppmuntrer traineens refleksjon over egen utvikling. Supervisor diskuterer forslag og erfaringer, men også hvordan traineen kan fremme sin egen læring." \n    }\n  ],\n  "limitations": [\n    "Manglet en bedre struktur på samtalen, som kunne ha gjort det lettere å følge diskusjonen",\n    "Supervisor kunne ha stilt flere spørsmål for å stimulere traineeens refleksjon"\n  ],\n  "summary": "Denne samtalen viser god bruk av empati og fokus på egne forslag. Supervisor ser på traineens perspektiv, respekterer deres erfaringer og oppmuntrer til egne refleksjoner. Men noen flere spørsmål eller en bedre struktur kunne gjort samtalen enda mer effektiv."\n}',
  },
  {
    response:
      '{\n  "title": "Evaluering av supervisionssamtale",\n  "introduction": "Velkommen til evaluering av denne supervisionssamtalen!",\n  "techniques": [\n    { \n      "name": "Aktiv lytting", \n      "description": "Supervisor følger nøye med på hva traineens sier og spør etter flere detaljer." \n    },\n    { \n      "name": "Refleksjon", \n      "description": "Supervisor oppmuntrer traineens refleksjon over egen utvikling og utfordringer." \n    },\n    { \n      "name": "Fokusering på styrker og muligheter", \n      "description": "Supervisor fokuserer på traineens styrker, likninger og muligheter for fremtidig utvikling." \n    }\n  ],\n  "limitations": [\n    "Supervisor kunne ha gått dypper inn i utfordringene rundt prioritering og planlegging av tid."\n  ],\n  "summary": "Denne samtalen viser gode bruk av aktiv lytting, refleksjon og fokus på styrker og muligheter. Supervisor bidrar til å øke traineens selvrefleksjon og fremme deres kompetanse."\n}',
  },
  {
    response:
      '{\n  "title": "Evaluering av supervisionssamtale",\n  "introduction": "Velkommen til evaluering av denne supervisionssamtalen!",\n  "techniques": [\n    { "name": "Aktiv lytting", "description": "Supervisor oppmuntrer traineens åpenhet og deler sin egen forståelse av situasjonen." },\n    { "name": "Strukturert refleksjon", "description": "Supervisor hjelper trainee til å identifisere utfordringer og prioriterte områder for utvikling." }\n  ],\n  "limitations": [\n    "Supervisor kunne ha fokusert mer på konkrete mål for fremtidig utvikling.",\n    "Manglet støtte for utvikling av trainees egen kapasitet til å planlegge og prioritere oppgaver."\n  ],\n  "summary": "Denne samtalen viser god bruk av aktive lytting og strukturert refleksjon, men kunne hatt mer fokus på konkrete mål for fremtidig utvikling."\n}',
  },
  {
    response:
      '{\n  "title": "Evaluering av supervisionssamtale",\n  "introduction": "Velkommen til evaluering av denne supervisionssamtalen!",\n  "techniques": [\n    { \n      "name": "Empati", \n      "description": "Supervisor ser på traineens perspektiv og uttrykker forståelse, f.eks. \'Så bra du liker å jobbe her\'." \n    },\n    { \n      "name": "Refleksjon", \n      "description": "Supervisor oppmuntrer traineens refleksjon over egen utvikling, f.eks. \'Hva slags ting er du usikker på?\'" \n    }\n  ],\n  "limitations": [\n    "Supervisor kunne ha fokusert mer på traineens egne forslag og planer for å løse utfordringene."\n  ],\n  "summary": "Denne samtalen viser god bruk av empati og refleksjon, men kunne hatt mer fokus på traineens forslag og planer for fremtidige arbeidsmetoder."\n}',
  },
  {
    response:
      '{\n  "title": "Evaluering av supervisionssamtale",\n  "introduction": "Velkommen til evaluering av denne supervisionssamtalen!",\n  "techniques": [\n    { "name": "Aktiv lytting", "description": "Veilederen lyttet nøye til lærlingens uttalelser og reflekterte over hva de sa." },\n    { "name": "Problemløsning", "description": "Lærlingen samtalen med å definere problemene og finne måter å løse dem på." },\n    { "name": "Self-refleksjon", "description": "Både veileder og lærling brukte self-refleksjon for å identifisere styrker og svakheter." }\n  ],\n  "limitations": [\n    "Veilederen kunne ha brukt mer strukturerte spørsmål til å fremme refleksjon hos lærlingen."\n  ],\n  "summary": "Denne samtalen viser gode bruk av aktiv lytting, problemløsning og self-refleksjon. Veilederen var i stand til å hjelpe lærlingen med å definere problemene og finne måter å løse dem på."\n}',
  },
];
